### ISSUE TITLE
[Meadow] Crash with woolen cow

### ISSUE THREAD

**Issue by benio1394** [satisfyu/Let-s-Do-Hub#109] opened 2024-07-12 09:19 UTC
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.18

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Meadow cow caused render issue that lead to crash

### Steps to Reproduce

Everything is expalined in pastebin

### Logs

https://pastebin.com/UpBQgWRQ

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment] 2024-07-13 10:41
Fixed inDev. Will be released later this week.

**Comment by benio1394** [comment] 2024-08-06 16:39
Unfortunably this error is still in the newest version

**Comment by satisfyu** [comment] 2024-08-09 07:03
I can't reproduce this :/

**Comment by benio1394** [comment] 2024-08-09 09:02
This is link for modpack that I'm using, where this bug happen https://modrinth.com/modpack/victoriacraft/version/1.1.1

**Comment by satisfyu** [comment] 2024-08-09 09:29
Clashes with HungryCows

**Comment by satisfyu** [comment] 2024-08-09 09:51
It's actually related to this issue here: 
https://github.com/pnk2u/hungrycows/blob/main/src/main/java/com/pnku/hungrycows/mixin/CowEntityMixin.java

The easiest solution would be (i guess) to add an additional check to this mixin so it does not interfere with any other entities that are not "StandardVanillaCowEntity" instances

**Closed** 2024-08-20 00:50 UTC
Labels: bug
