### ISSUE TITLE
Villagers refuse to gain new profession

### ISSUE THREAD

**Issue by zeroneon** [satisfyu/Let-s-Do-Hub#62] opened 2024-06-04 01:43 UTC
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.2.12

### Issue Description

I am using this in a modpack and after pain stakingly removing one mod after another it seems that Candlelight has been causing all villagers in the world to refuse to learn a new profession.
LWJGL 3: 3.3.1
Forge: 47.2.20
Here are th mods used:
![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/62841053/9e5a1b6b-bf67-4ce5-ac37-1890d79b2475)

### Steps to Reproduce

1)Use the mods 
2)watch the villagers be lazy

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment] 2024-06-04 06:10
Pretty sure this was fixed in 1.2.12.1: 
https://www.curseforge.com/minecraft/mc-mods/lets-do-candlelight/files/5322893
https://modrinth.com/mod/lets-do-candlelight/version/1.2.12.1

**Comment by satisfyu** [comment] 2024-06-05 08:23
I've just checked it myself by using Version 1.2.12.1 and it works as intended.

**Closed by satisfyu** 2024-06-05 08:23 UTC
