### ISSUE TITLE
Backpack disappearing in trinket slot

### ISSUE THREAD

**Issue by ThunderBangGaming** [satisfyu/Let-s-Do-Hub#253] opened 2024-08-28 07:28 UTC
### Minecraft Version

Fabric 1.20.1

### Mod

Camping

### Mod Version

1.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

all backpacks except the enderbags disappear from the trinket slot upon opening the inventory but works perfectly fine in the chest slot and will work perfectly in the trinket slot after use in the chest slot

### Steps to Reproduce

1. equip a backpack in the trinket slot
2. press 'B'
3. disappears
4. then equip a backpack in the chest slot
5.  press 'B'
6. works fine in both slots

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by ThunderBangGaming** [comment] 2024-08-29 04:08
found out after awhile the backpack still disappears.

**Comment by Gl0wstone** [comment] 2024-09-04 19:13
Can confirm the backpack disappearing issue on the same mod version 1.0.3 on the same Minecraft version 1.20.1 for Fabric.

**Comment by lumpenprol** [comment] 2024-09-14 22:02
I too am still having this issue with the same versions of the mod and Minecraft but only with the small, hiking, and wandering bags. the goodies and end bags work as intended.

**Comment by AlyceOsbourne** [comment] 2024-09-15 04:00
Can also confirm this is still occuring.

**Comment by ProfessorPasta** [comment] 2024-09-20 03:01
Issue is still occurring in version 1.0.3 for Fabric. When equipping a backpack in the back slot and putting items in the inventory, and then exiting, it removes all other equipped trinkets and itself.

**Comment by OfficialLahusa** [comment] 2024-10-06 22:01
I can confirm the deletion of trinkets when removing the enderpack from the back trinket slot is an issue on Fabric 1.20.1. From my research the bug occurs on [line 24](https://github.com/satisfyu/Camping/blob/948a08d85d54c2b426387c51f777499469ecc494/fabric/src/main/java/net/satisfy/camping/fabric/compat/trinkets/BackpackTrinket.java#L24C1-L24C66) of `BackpackTrinket.onUnequip(ItemStack, SlotReference, LivingEntity)`, because the 0th slot of **every** trinket inventory is deleted. The [TrinketComponent API](https://github.com/emilyploszaj/trinkets/blob/main/src/main/java/dev/emi/trinkets/api/TrinketComponent.java) states the following about `TrinketComponent.getInventory()`, which returns a `Map<String, Map<String, TrinketInventory>>`:
> A map of slot group names, to slot names, to trinket inventories for the entity.

This is not how the given code utilizes it. Instead, it iterates over **all** trinket inventories and deletes the entry at `slot.index()`, which is 0. I have validated this using debug output and [Artifacts](https://modrinth.com/mod/artifacts) as a [Trinkets](https://www.curseforge.com/minecraft/mc-mods/trinkets) content addon mod to provide some deletable items. When equipping the artifacts and ender bag in their trinket slots and subsequently unequipping the latter, this is how the trinket component is processed:

> Slot Index: 0
>- Group: head
>    - Inventory: hat
>        - Deleting Item: 1 night_vision_goggles
>- Group: feet
>    - Inventory: shoes
>        - Deleting Item: 1 running_shoes
>- Group: chest
>    - Inventory: back
>        - Deleting Item: 0 air
>    - Inventory: necklace
>        - Deleting Item: 1 lucky_scarf
>- Group: legs
>    - Inventory: belt
>        - Deleting Item: 1 antidote_vessel
>- Group: offhand
>    - Inventory: glove
>        - Deleting Item: 1 pocket_piston
>- Group: hand
>    - Inventory: glove
>        - Deleting Item: 1 pickaxe_heater

It also seems as though the enderpack itself isn't part of the inventory anymore at the time that `onUnequip(...)` is called. This makes the entire iteration procedure redundant and can be removed entirely, which fixes the issue.

I would also like to point out, that the file [BackpackTrinket.java](https://github.com/satisfyu/Camping/blob/948a08d85d54c2b426387c51f777499469ecc494/fabric/src/main/java/net/satisfy/camping/fabric/compat/trinkets/BackpackTrinket.java) contains a whole lot of other semi-related issues:
- The `tick` method is entirely redundant.
- The `alreadyEquippedBackpack` method uses a length 1 `boolean[]` instead of a `boolean`

**Comment by satisfyu** [comment] 2024-10-19 07:26
Phew. First of all: Thank you all for your understanding, patience, and for breaking down this issue. :)

I’ve been somewhat time-constrained over the past few weeks and occasionally a bit less motivated to work on the Let's Do Mods - but I have now found and fixed the root cause. In version 1.0.4, everything should work as usual.

Special thanks to @OfficialLahusa.

**Comment by satisfyu** [comment] 2024-10-19 08:19
Fixed in 1.0.4.

**Closed by satisfyu** 2024-10-19 08:19 UTC
