### ISSUE TITLE
After any large modpacks are installed with letsDOs-farm_and_Charm, use REI to view any item labels causing the game to stall

### ISSUE THREAD

**Issue by LimitXiaoHuoChai** [satisfyu/Let-s-Do-Hub#326] opened 2024-10-20 01:48 UTC
### Minecraft Version

1.20.1fabric

### Mod

Farm and Charm

### Mod Version

letsdo-farm_and_charm-fabric-1.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

letsdo-farm_and_charm-fabric-1.0.3 is installed, enabling this feature on Roughly Enough Items in some modpacks over 200mod, viewing the label of any item will cause stalling or even unresponsiveness
![898b87d6083a79c3caeab818dc1f8e02](https://github.com/user-attachments/assets/d59d8aca-5647-4c32-bf6a-682d6a5d5381)

### Steps to Reproduce

letsdo-farm_and_charm-fabric-1.0.3 Open integrated display in any modpack with more than 200mod and view item labels including vanilla item labels will be stuck or even not respond. Remove letsdo-farm_and_charm-fabric-1.0.3 to view labels

### Logs

It only causes the game to stall, it does not cause the game to crash, I suspect that the lack of category tag caused a lot of stalls to load in a moment

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment] 2024-10-21 09:36
@LimitXiaoHuoChai 
Please send me your latest log (or the log when this is happening).

**Comment by satisfyu** [comment] 2024-12-13 17:35
No additional logs were provided despite follow-up requests. I was unable to reproduce the issue (both in a dev environment and in a small modpack).

Therefore, I will close this issue for now. If you provide the logs later, I am happy to reopen it (or you can create a new one).

**Closed by satisfyu** 2024-12-13 17:35 UTC
Labels: bug, wontfix, information needed
