### ISSUE TITLE
Apples and product disappear after closing apple press UI

### ISSUE THREAD

**Issue by Cafftac** [satisfyu/Let-s-Do-Hub#78] opened 2024-06-16 00:12 UTC
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.19

### Latest Version

- [ ] Yes. I'm using the latest Version.

### Issue Description

When I place apples in the apple press and then close the apple press menu, the apples disappear

### Steps to Reproduce

-Place apple press
-Put in apples
-Close apple press
-Open press again and see that it's empty

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment] 2024-06-16 13:27
Please update to the latest version and test it on a minimal instance, thank you.

**Comment by satisfyu** [comment] 2024-06-24 09:06
Closing this issue since i havent being able to reproduce it and no additional informations have been provided.

**Closed by satisfyu** 2024-06-24 09:06 UTC
