### ISSUE TITLE
Crafting is not progressing on multi-server with many mods.

### ISSUE THREAD

**Issue by picpic779** [satisfyu/Let-s-Do-Hub#13] opened 2024-05-03 22:49 UTC
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.1.8

### Issue Description

When I try to use the stove or cooking pot to make jam or food, the craft does not progress. This only occurs on the server and when I experimented with a single I was able to make it successfully.

I am reporting this just in case it is something that may be unavoidable as I have a lot of mods in the system.

### Steps to Reproduce

[main/INFO]: Loading 420 mods:
	- additionaladditions 6.0.1
	- adventurez 1.4.20
	- amarite 1.0.8
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   \-- reach-entity-attributes 2.4.0
	- another_furniture 1.20.1-3.0.1
	- archers 1.2.1+1.20.1
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- architectury 9.2.14
	- artifacts 9.4.3
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- expandability 9.0.0
	   \-- step-height-entity-attribute 1.2.0
	- athena 3.1.2
	- attributefix 21.0.4
	- automobility 0.4.2+1.20.1-fabric
	   \-- jsonem 0.2.1+1.20
	- azurelib 2.0.20
	- azurelibarmor 2.0.3
	- bakery 1.1.8
	- balm-fabric 7.2.2
	- bclib 3.0.14
	   \-- wunderlib 1.1.5
	- beachparty 1.1.4
	- beautify 1.1.0+1.20
	- beetlebox 1.1.1
	   \-- com_google_code_findbugs_jsr305 3.0.2
	- betterarcheology 1.1.8-1.20.1
	- bettercombat 1.8.5+1.20.1
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterdogs_dtn ${version}
	- betterend 4.0.11
	- betterendisland 1.20-Fabric-2.0.6
	- betterfortresses 1.20-Fabric-2.0.6
	- betterjungletemples 1.20-Fabric-2.0.4
	- bettermineshafts 1.20-Fabric-4.0.4
	- betternether 9.0.10
	- betteroceanmonuments 1.20-Fabric-3.0.4
	- betterstrongholds 1.20-Fabric-4.0.3
	- betterthanmending 1.3.0
	- bosses_of_mass_destruction 1.7.5-1.20.1
	   |-- maelstrom_library 1.6.1-1.20
	   \-- multipart_entities 1.5-1.20
	- botania 1.20.1-443-FABRIC
	   |-- fiber 0.23.0-2
	   |-- reach-entity-attributes 2.4.0
	   \-- step-height-entity-attribute 1.2.0
	- bountiful 6.0.3+1.20.1
	- brewery 1.1.5
	- c2me 0.2.0+alpha.11.5
	   |-- c2me-base 0.2.0+alpha.11.5
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.5
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.5
	   |-- c2me-notickvd 0.2.0+alpha.11.5
	   |-- c2me-opts-allocs 0.2.0+alpha.11.5
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.5
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.5
	   |-- c2me-opts-math 0.2.0+alpha.11.5
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.5
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.5
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.5
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.5
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.5
	   |-- c2me-server-utils 0.2.0+alpha.11.5
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.5
	   |-- c2me-threading-lighting 0.2.0+alpha.11.5
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- candlelight 1.2.11
	- cardinal-components 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- carryon 2.1.2.7
	- casualness_delight 1.20.1-0.4-final
	- caveoverhaul fabric-1.20.1-1.2.2
	- chefsdelight 1.0.3-fabric-1.20.1
	- chimes 2.0.1
	- chipped 3.0.6
	- chunky 1.3.138
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- contact 1.2.0-Beta
	- convenientdecor 0.4.1
	   \-- omega-config 1.4.0+1.20.1
	- corgilib 4.0.1.1
	   |-- com_electronwill_night-config_core 3.6.7
	   \-- com_electronwill_night-config_toml 3.6.7
	- coroutil 1.20.1-1.3.7
	- cosmetic-armor 1.6.0
	- cratedelight 1.4.5-1.20.1-fabric
	- create 0.5.1-f-build.1417+mc1.20.1
	   |-- flywheel 0.6.10-2
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_base 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_config 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    |-- porting_lib_fluids 2.3.2+1.20.1
	   |    |-- porting_lib_lazy_registration 2.3.2+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.2+1.20.1
	   |    |-- porting_lib_utility 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_brewing 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_client_events 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_entity 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.3.2+1.20.1
	   |-- porting_lib_extensions 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_models 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    |-- porting_lib_fluids 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_networking 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_obj_loader 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_tool_actions 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_transfer 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_fluids 2.3.2+1.20.1
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        |    \-- porting_lib_gametest 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             |-- porting_lib_gametest 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create_dd 0.1b
	   \-- dsbg 1.0
	- createaddition 1.2.3
	- createdeco 2.0.2-1.20.1-fabric
	- createfood 1.0.6
	- creeperoverhaul 3.0.2
	- ctov 3.4.3
	- culturaldelights 0.14.12+1.20.1
	   \-- terraform-wood-api-v1 7.0.1
	- cupboard 1.20.1-2.6
	- dahmersdelight 1.0.1
	- darktimer 1.1.0
	- dehydration 1.3.6
	- delightfulcreators 1.1.8
	- doapi 1.2.9
	   \-- terraform-wood-api-v1 7.0.1
	- doggytalents 1.18.10
	- dummmmmmy 1.20-1.8.14
	- dungeon_difficulty 2.1.0+1.20.1
	- dungeons_arise 2.1.58
	- emotecraft 2.2.7-b.build.50
	   \-- bendy-lib 4.0.0
	- endermanoverhaul 1.0.4
	- enderzoology 8.0.2
	- epicsamurai 0.0.5-beta
	- expandeddelight 0.3.0.3
	- explorify v1.3.0-mc1.20
	- exposure 1.5.1
	- extended_drawers 2.1.1+mc.1.20.1
	   |-- config_toolkit 1.0.0
	   |    |-- io_determann_shadow-api-17 0.1.1
	   |    \-- net_fabricmc_javapoet 0.1.0
	   |-- graphlib 1.4.0+1.20
	   |    |-- kmodlib-overlay 0.2.12+1.20
	   |    \-- libnetworkstack 0.10.0
	   \-- noindium 1.1.0+1.20
	- extraalchemy 1.10.0
	- extraordinary_extra_totems 1.0.3
	- fabric-api 0.92.1+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.10
	   \-- mixinextras 0.3.5
	- farmersdelight 1.20.1-1.4.3
	- ferritecore 6.0.1
	- forgeconfigapiport 8.0.0
	- friendsandfoes 2.0.10
	- frightsdelight fabric-1.20.1-1.0.4
	- fruitfulfun 7.3.4
	- fsit v2.1.0+1.20.1
	   |-- com_charleskorn_kaml_kaml-jvm 0.54.0
	   \-- org_snakeyaml_snakeyaml-engine 2.6
	- ftblibrary 2001.2.0
	- ftbultimine 2001.1.4
	- galosphere 1.20.1-1.4.1
	   \-- mm 2.3
	- geckolib 4.4.4
	   \-- com_eliotlash_mclib_mclib 20
	- grapplemod 1.99.0+1.20.1.beta.fabric
	- graveyard 3.0
	- handcrafted 3.0.6
	- hardcorerevival 12.0.2
	- harvestwithease 8.0.1.0
	- heartbond 1.6.0
	- heartstone 1.20-1.3.0
	- herbalbrews 1.0.6
	- horseshoes 1.0.2
	- hybrid-aquatic 1.3.2
	   |-- mixinextras 0.3.5
	   \-- reach-entity-attributes 2.4.0
	- illagerinvasion 8.0.4
	   \-- extensibleenums 7.0.1
	- immersive_aircraft 0.7.5+1.20.1
	   \-- org_mariuszgromada_math_mathparser_org-mxparser 5.2.1
	- immersive_armors 1.6.1+1.20.1
	- immersive_melodies 0.1.0+1.20.1
	- infinitybuttons 4.0.1-mc1.20.1
	- insanetnt 1.4
	- interiors 0.5.3+fabric-mc1.20.1
	- invoke 0.2.3
	- jade 11.8.0
	- jaizmobs 1.1-1.20.1
	- jamlib 0.6.1+1.20.x
	- java 18
	- jewelry 1.3.0+1.20.1
	- journeymap 5.9.21
	   \-- journeymap-api-fabric 1.20-1.9-fabric-SNAPSHOT
	- justoutdoorstuffs 1.0.2
	- kambrik 6.1.1+1.20.1
	- kiwi 11.6.0
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lazydfu 0.1.3
	- letsdoaddon-compat 1.4.1
	- lithium 0.11.2
	- lithostitched 1.1.5
	- lychee 5.1.11
	- man_of_many_planes 0.0.3+1.20.1
	- mcwwindows 2.2.1
	- meadow 1.3.8
	- memoryleakfix 1.1.5
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- mobtimizations 1.20.1-1.0.0
	- moonlight 1.20-2.11.12
	- moredelight 1.2.1-1.20.1-fabric
	- mr_advancement_count 1-v1.1.0b
	- mr_dungeons_andtavernsancientcityoverhaul 1
	- mr_ns_fdrc 0.0.1
	- mr_true_ending 1-v1.1.0c
	- mutantmonsters 8.0.7
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   \-- extensibleenums 7.0.1
	- mvs 4.1.2-1.20-fabric
	- mythicmounts 1.20.1-7.2
	- naturalist 4.0.3
	- natures_spirit 1.4.3.1.20.1
	- naturescompass 1.20.1-2.2.3-fabric
	- nethersdelight 1.0.0
	   \-- disable_custom_worlds_advice 4.1
	- nethervinery 1.2.9
	- noisium 2.0.2+mc1.20-1.20.1
	   \-- mixinextras 0.3.5
	- openblocks 0.0.3-1.20.1
	- owo 0.11.2+1.20
	- paladins 1.2.0+1.20.1
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- patchouli 1.20.1-84-FABRIC
	   \-- fiber 0.23.0-2
	- pickupnotifications 1.5.2
	- piercingpaxels 1.0.12
	- ping-wheel 1.8.0
	- player-animator 1.0.2-rc1+1.20
	- polymorph 0.49.3+1.20.1
	   \-- spectrelib 0.13.15+1.20.1
	- puffish_skills 0.11.6
	- puzzleslib 8.1.18
	   \-- puzzlesaccessapi 8.0.7
	- rain-grow 1.2
	- ranged_weapon_api 1.1.1+1.20.1
	- recipeessentials 1.20.1-3.3
	- redbits-common 1.16.3
	   \-- redbits 1.16.3
	        \-- interference 1.7.0
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.24
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- runes 0.9.11+1.20.1
	- sawmill 1.20-1.3.11
	- sculkhornid 1.4.1
	- servercore 1.5.0+1.20.1
	   |-- fabric-permissions-api-v0 0.3-SNAPSHOT
	   |-- org_yaml_snakeyaml 2.2
	   |-- placeholder-api 2.1.3+1.20.1
	   |-- space_arim_dazzleconf_dazzleconf-core 1.3.0-M2
	   \-- space_arim_dazzleconf_dazzleconf-ext-snakeyaml 1.3.0-M2
	- silveroak 1.1.0-Alpha
	- simplebackup 2.0-1.20
	   |-- com_github_spoorn_tar-lz4-java 1.0.3
	   \-- net_lingala_zip4j_zip4j 2.11.5
	- simplehats 1.20.1-0.2.4
	- simplemod 1.20.1
	- simplyskills 1.3.2+1.20.1
	- simplyswords 1.55.0-1.20.1
	   \-- spruceui 5.0.0+1.20
	- sliceanddice 3.1.1
	- smartbrainlib 1.13
	- sn0wfrogs_capybaras 1.1.0-mc1.20.1
	- snifferplus 0.2.0
	- soulsweapons 1.1.3-1.20-fabric
	- spark 1.10.53
	- spell_engine 0.14.3+1.20.1
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- spell_power 0.10.2+1.20.1
	- spiceoffabric 1.6.2+mc1.20.1
	   |-- capsaicin 1.3.3+mc1.20.1
	   |-- coat 1.0.0-beta.20+mc1.20-pre1
	   |-- tweed4_annotated 1.3.1+mc1.20-pre1
	   |-- tweed4_base 1.7.1+mc1.20-pre1
	   |-- tweed4_data 1.2.1+mc1.20-pre1
	   |-- tweed4_data_hjson 1.1.1+mc1.20-pre1
	   |-- tweed4_tailor_coat 1.1.3+mc1.20-pre1
	   |-- tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
	   \-- tweed4_tailor_screen 1.1.4+mc1.20-pre1
	- storagebox 1.4.0-1.20.1
	- storagedelight 1.0.3-1.20.1-fabric
	- structure_pool_api 1.0+1.20.1
	- structureessentials 1.20.1-3.3
	- supplementaries 1.20-2.8.10
	   \-- mixinsquared 0.1.1
	- swampier_swamps 1.20-4.0.0
	- tabtps-fabric 1.3.18
	   |-- adventure-platform-fabric 5.10.0-SNAPSHOT
	   |    |-- net_kyori_adventure-api 4.14.0
	   |    |-- net_kyori_adventure-key 4.14.0
	   |    |-- net_kyori_adventure-platform-api 4.3.0
	   |    |-- net_kyori_adventure-text-logger-slf4j 4.14.0
	   |    |-- net_kyori_adventure-text-minimessage 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-ansi 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-gson 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-json 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-plain 4.14.0
	   |    |-- net_kyori_ansi 1.0.1
	   |    |-- net_kyori_examination-api 1.3.0
	   |    \-- net_kyori_examination-string 1.3.0
	   |-- cloud 1.8.3
	   |    |-- cloud_commandframework_cloud-brigadier_ 1.8.3
	   |    |-- cloud_commandframework_cloud-core_ 1.8.3
	   |    |-- cloud_commandframework_cloud-services_ 1.8.3
	   |    \-- io_leangen_geantyref_geantyref 1.3.13
	   |-- cloud_commandframework_cloud-minecraft-extras 1.8.3
	   |-- com_typesafe_config 1.4.2
	   |-- net_kyori_adventure-serializer-configurate4 4.14.0
	   |-- net_kyori_adventure-text-feature-pagination 4.0.0-SNAPSHOT
	   |-- net_kyori_adventure-text-serializer-legacy 4.14.0
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- terrablender 3.0.1.4
	   |-- com_electronwill_night-config_core 3.6.7
	   \-- com_electronwill_night-config_toml 3.6.7
	- terralith 2.4.11
	- the_bumblezone 7.3.5+1.20.1-fabric
	   |-- mixinextras 0.3.5
	   \-- noindium 1.1.0+1.20
	- threadtweak 1.20.2-0.1.1
	- toms_storage 1.6.6
	- torchbowmod 1.0
	- torches_in_water 0.2.2
	   \-- phoupraws_linked_lib 0.14.0
	        \-- team_reborn_energy 3.0.0
	- travelersbackpack fabric-1.20.1-9.1.12
	   \-- reach-entity-attributes 2.4.0
	- trinkets 3.7.2
	- turkish_delight 1.0.0
	- ubesdelight fabric-1.20.1-0.1.5.3
	- ultris_mr 5.6.9c
	- umu_little_maid 3.11a
	- underground_jungle 20.1.2
	- vanilla_claws 1.1
	   \-- reach-entity-attributes 2.4.0
	- variantvanillablocks 1.3.8
	- vc_gliders 1.1.5
	   \-- palladiumcore 1.20-2.0.0.0
	- verdantvibes 1.0.1-1.20.1
	- vinery 1.4.14
	- warriorrage 1.20.1-fabric-1.0.0
	- watut 1.20.1-1.1.1
	- waystones 14.1.3
	- wetlands 1.2
	- wheelbarrow 1.0.0
	- wizards 1.2.0+1.20.1
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- yet_another_config_lib_v3 3.2.2+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yigd 2.0.0-beta.11
	   \-- libgui 8.1.1+1.20.1
	        |-- jankson 6.0.0+j1.2.3
	        |    \-- blue_endless_jankson 1.2.3
	        \-- libninepatch 1.2.0
	- yungsapi 1.20-Fabric-4.0.4
	   \-- org_javassist_javassist 3.29.2-GA

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by orionSquared** [comment] 2024-05-04 04:07
Can confirm. Playing on a server with some friends in the BigChadGuys modpack and the stove isn't baking simple bread despite the recipe being correct.

**Comment by satisfyu** [comment] 2024-05-07 07:53
I'll take a closer look into this the upcoming weekend.

**Comment by satisfyu** [comment] 2024-05-07 12:16
I've just downloaded the BigChadGuys modpack and it seems like everything works as it should. Was able to make Jam, Cornets, Bread, etc.

**Comment by SithLordLuxray** [comment] 2024-05-26 20:07
Having the same issue with a BigChadGuys server. Stove works for the most part, cooking pots are inoperative due to them not progressing.

**Comment by Ninjdai1** [comment] 2024-05-31 08:11
Some of this issues issues were likely caused by the letsdo compat addon
Fixed indev, will release the fix soon

**Comment by satisfyu** [comment] 2024-06-02 21:21
It seems indeed to be related to the Compat Addon. :) Adding it wont let me process certain items anymore. 

So let's wait for Ninjadai's Update and we can finally close this issue.

**Comment by Ninjdai1** [comment] 2024-06-03 19:45
The compat addon was updated and as of my and some people's testing the recipes seem to all be fixed.

**Closed** 2024-06-04 21:10 UTC
Labels: bakery, cant reproduce
