### ISSUE TITLE
 [Let's Do] Furniture causing mining fatigue on new launch.

### ISSUE THREAD

**Issue by ozmly** [satisfyu/Let-s-Do-Hub#383] opened 2024-12-05 22:50 UTC
### Minecraft Version

1.20.1

### Mod

Furniture

### Mod Version

1.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Every time the game was launched whatever save I loaded into i gained mining fatigue. Would only clear when i save the world exit and rejoin. Was not able to pinpoint a log error or cause. It is a mod incompatibility with one of the other 302 mods. I checked every mod, and having [Let's Do] Furniture causes it. I tried with only  [Let's Do] Furniture and its dependents, and no issue. 

### Steps to Reproduce

Have [Let's Do] Furniture1.0.3 and these mods: accessories: 1.0.0-beta.41+1.20.1  adorabuild_structures: 2.8.0  advanced_runtime_resource_pack: 0.8.0  almanac: 1.0.2  alternate-current: 1.9.0  ambientsounds: 6.1.3  amendments: 1.20-1.2.12  animal_feeding_trough: 1.1.0+1.20.1  animatica: 0.6.1+1.20.4  another_furniture: 1.20.1-3.0.1  appleskin: 2.5.1+mc1.20  architectury: 9.2.14  asynclocator: 1.3.0  autoslabs: 1.1.3  backpacked: 2.2.7  badpackets: 0.4.3  bakery: 1.1.15  balm-fabric: 7.0.7  barteringstation: 8.0.0  bbb: 1.20.1-fabric-1.0.2  bclib: 3.0.14  beautify: 1.2.0+1.20.1  bendy-lib: 4.0.0  better-trim-tooltips: 1.0.1  betteradvancements: 0.4.2.10  betterarcheology: 1.2.1-1.20.1  bettercombat: 1.8.6+1.20.1  betterdeserttemples: 1.20-Fabric-3.0.3  betterdungeons: 1.20-Fabric-4.0.4  betterend: 4.0.11  betterendisland: 1.20-Fabric-2.0.6  betterfortresses: 1.20-Fabric-2.0.6  betterjungletemples: 1.20-Fabric-2.0.5  bettermineshafts: 1.20-Fabric-4.0.4  betternether: 9.0.10  betteroceanmonuments: 1.20-Fabric-3.0.4  betterstrongholds: 1.20-Fabric-4.0.3  betterthirdperson: 1.9.0  bettertridents: 8.0.1  betterwitchhuts: 1.20-Fabric-3.0.3  biolith: 1.0.0-beta.2  biomeswevegone: 1.4.4  blockrunner: 8.0.4  bloomingnature: 1.0.9  blue_endless_jankson: 1.2.3  boatbreakfix: 1.0.2  boatiview: 0.0.5  bountiful: 6.0.4+1.20.1  bygonenether: 1.3.2  c2me: 0.2.0+alpha.11.5  c2me-base: 0.2.0+alpha.11.5  c2me-client-uncapvd: 0.2.0+alpha.11.5  c2me-fixes-chunkio-threading-issues: 0.2.0+alpha.11.5  c2me-fixes-general-threading-issues: 0.2.0+alpha.11.5  c2me-fixes-worldgen-threading-issues: 0.2.0+alpha.11.5  c2me-fixes-worldgen-vanilla-bugs: 0.2.0+alpha.11.5  c2me-notickvd: 0.2.0+alpha.11.5  c2me-opts-allocs: 0.2.0+alpha.11.5  c2me-opts-chunk-access: 0.2.0+alpha.11.5  c2me-opts-chunkio: 0.2.0+alpha.11.5  c2me-opts-math: 0.2.0+alpha.11.5  c2me-opts-scheduling: 0.2.0+alpha.11.5  c2me-opts-worldgen-general: 0.2.0+alpha.11.5  c2me-opts-worldgen-vanilla: 0.2.0+alpha.11.5  c2me-rewrites-chunk-serializer: 0.2.0+alpha.11.5  c2me-rewrites-chunkio: 0.2.0+alpha.11.5  c2me-server-utils: 0.2.0+alpha.11.5  c2me-threading-chunkio: 0.2.0+alpha.11.5  c2me-threading-lighting: 0.2.0+alpha.11.5  c2me-threading-worldgen: 0.2.0+alpha.11.5  caffeineconfig: 1.3.0+1.17  cardinal-components-base: 5.2.2  cardinal-components-block: 5.2.1  cardinal-components-entity: 5.2.2  cardinal-components-item: 5.2.2  cavedust: 3.0.0  charm: forked-6.0.23  charmony: 6.15.1  chat_heads: 0.13.7  chunky: 1.3.146  citresewn: 1.2.2+1.20.1  citresewn-defaults: 1.2.2+1.20.1  clean-debug: 0.4.8  cloth-basic-math: 0.6.1  cloth-config: 11.1.136  cloth-config: 11.1.136  clumps: 12.0.0.4  collective: 7.87  com_akuleshov7_ktoml-core-jvm: 0.5.2  com_electronwill_night-config_core: 3.8.0  com_electronwill_night-config_hocon: 3.8.0  com_electronwill_night-config_json: 3.8.0  com_electronwill_night-config_toml: 3.8.0  com_electronwill_night-config_yaml: 3.8.0  com_eliotlash_mclib_mclib: 20  com_github_keksuccino_japng: 0.5.3  com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-1.7  com_ibm_async_asyncutil: 0.1.0  com_moandjiezana_toml_toml4j: 0.7.2  com_teamresourceful_bytecodecs: 1.0.2  com_teamresourceful_yabn: 1.0.3  com_twelvemonkeys_common_common-image: 3.10.0  com_twelvemonkeys_common_common-io: 3.10.0  com_twelvemonkeys_common_common-lang: 3.10.0  com_twelvemonkeys_imageio_imageio-core: 3.10.0  com_twelvemonkeys_imageio_imageio-metadata: 3.10.0  com_twelvemonkeys_imageio_imageio-webp: 3.10.0  com_velocitypowered_velocity-native: 3.2.0-SNAPSHOT  comforts: 6.4.0+1.20.1  common-protection-api: 1.0.0  commonnetworking: 1.0.5-1.20.1  conditional-mixin: 0.5.1  controlling: 12.0.2  corgilib: 4.0.3.2  coroutil: 1.20.1-1.3.7  crawl: 0.12.0  creativecore: 2.12.23  creeperoverhaul: 3.0.2  cristellib: 1.1.5  crowdin-translate: 1.4+1.19.3  cull-less-leaves: 1.4.2+1.21-fabric  customfov: 6.2.1+1.20.1  customportalapi: 0.0.1-beta64-1.20  cutthrough: 8.0.2  darkness: 1.2.0  debugify: 1.20.1+2.0  decorative_blocks: 4.1.3  deeperdarker: 1.3.2.1  deuf_refabricated: 1.1.0  diagonalblocks: 8.0.6  diagonalfences: 8.1.5  diagonalwalls: 8.0.4  diagonalwindows: 8.1.5  distanthorizons: 2.1.0-a  doapi: 1.2.15  dragonloot: 1.1.4  dynamictrim: 1.4.1  e4mc_minecraft: 5.2.1  easyanvils: 8.0.2  easymagic: 8.0.1  easyshulkerboxes: 8.0.2  eatinganimationid: 1.20+1.9.61  ec-core: 1.3.0-mc1.20.1  emotecraft: 2.2.7-b.build.50  emotetweaks: 4.0.3.37  endermanoverhaul: 1.0.4  ends_delight: refabricated-1.20.1-2.5  enhancedblockentities: 0.9+1.20  entity_model_features: 2.2.6  entity_texture_features: 6.2.8  entityculling: 1.7.1  error_notifier: 1.0.9  essential_commands: 0.35.3-mc1.20.1  everycomp: 1.20-2.6.94  expandeddelight: 0.3.2  explosiveenhancement: 1.2.2-1.20.x  exposure: 1.7.7  extensibleenums: 7.0.1  fabric-api: 0.92.2+1.20.1  fabric-api: 0.92.2+1.20.1  fabric-api-base: 0.4.31+1802ada577  fabric-api-lookup-api-v1: 1.6.36+1802ada577  fabric-biome-api-v1: 13.0.13+1802ada577  fabric-block-api-v1: 1.0.11+1802ada577  fabric-block-view-api-v2: 1.0.1+1802ada577  fabric-blockrenderlayer-v1: 1.1.41+1802ada577  fabric-client-tags-api-v1: 1.1.2+1802ada577  fabric-command-api-v1: 1.2.34+f71b366f77  fabric-command-api-v2: 2.2.13+1802ada577  fabric-commands-v0: 0.2.51+df3654b377  fabric-containers-v0: 0.1.64+df3654b377  fabric-content-registries-v0: 4.0.11+1802ada577  fabric-convention-tags-v1: 1.5.5+1802ada577  fabric-crash-report-info-v1: 0.2.19+1802ada577  fabric-data-attachment-api-v1: 1.0.0+de0fd6d177  fabric-data-generation-api-v1: 12.3.4+1802ada577  fabric-dimensions-v1: 2.1.54+1802ada577  fabric-entity-events-v1: 1.6.0+1c78457f77  fabric-events-interaction-v0: 0.6.2+1802ada577  fabric-events-lifecycle-v0: 0.2.63+df3654b377  fabric-game-rule-api-v1: 1.0.40+1802ada577  fabric-item-api-v1: 2.1.28+1802ada577  fabric-item-group-api-v1: 4.0.12+1802ada577  fabric-key-binding-api-v1: 1.0.37+1802ada577  fabric-keybindings-v0: 0.2.35+df3654b377  fabric-language-kotlin: 1.13.0+kotlin.2.1.0  fabric-lifecycle-events-v1: 2.2.22+1802ada577  fabric-loot-api-v2: 1.2.1+1802ada577  fabric-loot-tables-v1: 1.1.45+9e7660c677  fabric-message-api-v1: 5.1.9+1802ada577  fabric-mining-level-api-v1: 2.1.50+1802ada577  fabric-model-loading-api-v1: 1.0.3+1802ada577  fabric-models-v0: 0.4.2+9386d8a777  fabric-networking-api-v1: 1.3.11+1802ada577  fabric-networking-v0: 0.3.51+df3654b377  fabric-object-builder-api-v1: 11.1.3+1802ada577  fabric-particles-v1: 1.1.2+1802ada577  fabric-permissions-api-v0: 0.3.1  fabric-recipe-api-v1: 1.0.21+1802ada577  fabric-registry-sync-v0: 2.3.3+1802ada577  fabric-renderer-api-v1: 3.2.1+1802ada577  fabric-renderer-indigo: 1.5.2+85287f9f77  fabric-renderer-registries-v1: 3.2.46+df3654b377  fabric-rendering-data-attachment-v1: 0.3.37+92a0d36777  fabric-rendering-fluids-v1: 3.0.28+1802ada577  fabric-rendering-v0: 1.1.49+df3654b377  fabric-rendering-v1: 3.0.8+1802ada577  fabric-resource-conditions-api-v1: 2.3.8+1802ada577  fabric-resource-loader-v0: 0.11.10+1802ada577  fabric-screen-api-v1: 2.0.8+1802ada577  fabric-screen-handler-api-v1: 1.3.30+1802ada577  fabric-sound-api-v1: 1.0.13+1802ada577  fabric-transfer-api-v1: 3.3.5+8dd72ea377  fabric-transitive-access-wideners-v1: 4.3.1+1802ada577  fabricloader: 0.16.9  fallingleaves: 1.15.6  fallingtrees: 0.12.7  fancymenu: 3.3.2  farmersdelight: 1.20.1-2.2.0+refabricated  faster-random: 5.1.0  ferritecore: 6.0.1  firstperson: 2.4.6  flowerpatch: 3.1.0  folk_sisby_kaleido-config: 0.3.1+1.3.1  forgeconfigapiport: 8.0.1  formations: 1.0.3  formationsnether: 1.0.5  formationsoverworld: 1.0.4  framework: 0.6.16  friendsandfoes: 3.0.6  frostiful: 1.0.11  fusion: 1.1.1  fwaystones: 3.3.2+mc1.20.1  fzzy_config: 0.5.8+1.20.1  geckoanimfix: 1.0.0  geckolib: 4.4.9  glitchcore: 0.0.1.1  golemfirststonemod: 0.0.11-1.20.1  grapplemod: 1.99.0+1.20.1.beta.fabric  grassseeds: 3.3  handcrafted: 3.0.6  hearth_and_home: 1.20.1-2.0.3  hearths: 1.0.1  herbalbrews: 1.0.8.1  highlighter: 1.1.9  hopobettermineshaft: 1.1.8  hopobetterruinedportal: 1.3.7  hopobetterunderwaterruins: 1.1.4  horseexpert: 8.1.1  hybrid-aquatic: 1.3.4  icarus: 2.10.0  iceberg: 1.1.25  illagerinvasion: 8.0.6  immediatelyfast: 1.3.2+1.20.4  immersive_weathering: 1.20.1-2.0.3  indium: 1.0.30+mc1.20.4  inventorymanagement: 1.3.1  io_github_douira_glsl-transformer: 2.0.0-pre13  io_wispforest_endec: 0.1.8  io_wispforest_endec_gson: 0.1.5  io_wispforest_endec_netty: 0.1.4  iris: 1.7.0+mc1.20.1  ironchests: 5.0.2  jamlib: 0.6.1+1.20.x  java: 17  kambrik: 6.1.1+1.20.1  kanos_config: 0.4.1+1.14.4-1.19.4  keybind_fix: 1.0.0  kirin: 1.15.6+1.20.1  knightlib: 1.1.0  knightquest: 1.7.2  konkrete: 1.8.1  krypton: 0.2.3  lambdynlights: 2.3.2+1.20.1  lazydfu: 0.1.3  leavesbegone: 8.0.0  legendarytooltips: 1.4.5  letmedespawn: 1.4.4  lithium: 0.11.2  lmft: 1.0.2+1.20  lootr: 0.7.33.81  macawsbridgesbyg: 1.20.1-1.1  magnumtorch: 8.0.2  mca: 7.5.21+1.20.1  mcwbridges: 3.0.0  melody: 1.0.3  memoryleakfix: 1.1.5  midnightlib: 1.4.1  minecraft: 1.20.1  mixinextras: 0.4.1  mixinsquared: 0.1.1  mixintrace: 1.1.1+1.17  mm: 2.3  modernfix: 5.19.5+mc1.20.1  modmenu: 7.2.2  moonlight: 1.20-2.13.33  moremobs: 1.5.3+mod  moremobvariants: 1.3.1  mousetweaks: 2.26  moveboats: 3.4  mr_camps_castles_carriages: 2.3.3  mr_crafting: 1.1  mr_dungeons_andtaverns: 3.0.3.f  mr_katters_structures: 1.6  mr_lukis_grandcapitals: 1.1.1  mysticsbiomes: 3.4.3  naturalist: 4.0.3  natures_spirit: 1.6.3-1.20.1  necronomicon: 1.6.0  net_jodah_typetools: 0.6.3  net_lenni0451_reflect: 1.3.4  net_minecraftforge_eventbus: 6.0.3  net_objecthunter_exp4j: 0.4.8  net_peanuuutz_tomlkt_tomlkt-jvm: 0.3.7  netherchested: 8.0.4  niftycarts: 20.1.3  nightautoconfig: 1.0.6  no-telemetry: 1.8.0  nochatreports: 1.20.1-v2.2.2  noisium: 2.0.3+mc1.20-1.20.1  notenoughanimations: 1.8.1  ohthetreesyoullgrow: 1.20.1-1.3.1  omega-config: 1.4.0+1.20.1  onlyexcavators: 1.20.1-0.6  org_anarres_jcpp: 1.4.14  org_antlr_antlr4-runtime: 4.11.1  org_apache_httpcomponents_httpmime: 4.5.10  org_javassist_javassist: 3.29.2-GA  org_jetbrains_kotlin_kotlin-reflect: 2.1.0  org_jetbrains_kotlin_kotlin-stdlib: 2.1.0  org_jetbrains_kotlin_kotlin-stdlib-jdk7: 2.1.0  org_jetbrains_kotlin_kotlin-stdlib-jdk8: 2.1.0  org_jetbrains_kotlinx_atomicfu-jvm: 0.26.1  org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: 1.9.0  org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: 1.9.0  org_jetbrains_kotlinx_kotlinx-datetime-jvm: 0.6.1  org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: 0.6.0  org_jetbrains_kotlinx_kotlinx-io-core-jvm: 0.6.0  org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: 1.7.3  org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: 1.7.3  org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: 1.7.3  org_quiltmc_parsers_gson: 0.2.1  org_quiltmc_parsers_json: 0.2.1  org_reflections_reflections: 0.10.2  org_threadly_threadly: 7.0  org_yaml_snakeyaml: 2.0  overflowingbars: 8.0.1  owo: 0.11.2+1.20  packet_tweaker: 0.4.0+1.19.4  pandalib: 0.4.2  particle_core: 0.2.5+1.20.1  pehkui: 3.8.3+1.14.4-1.21  ping-wheel: 1.10.0  placeholder-api: 2.1.3+1.20.1  player-animator: 1.0.2-rc1+1.20  playerabilitylib: 1.8.0  polymer-common: 0.5.19+1.20.1  polymer-core: 0.5.19+1.20.1  polymer-networking: 0.5.19+1.20.1  polymer-registry-sync-manipulator: 0.5.19+1.20.1  polymer-resource-pack: 0.5.19+1.20.1  polymer-virtual-entity: 0.5.19+1.20.1  polymorph: 0.49.7+1.20.1  porting_lib_accessors: 2.3.4+1.20.1  porting_lib_attributes: 2.3.4+1.20.1  porting_lib_base: 2.3.4+1.20.1  porting_lib_common: 2.3.4+1.20.1  porting_lib_config: 2.3.4+1.20.1  porting_lib_core: 2.3.4+1.20.1  porting_lib_entity: 2.3.4+1.20.1  porting_lib_extensions: 2.3.4+1.20.1  porting_lib_fluids: 2.3.4+1.20.1  porting_lib_lazy_registration: 2.3.4+1.20.1  porting_lib_loot: 2.3.4+1.20.1  porting_lib_mixin_extensions: 2.3.4+1.20.1  porting_lib_networking: 2.3.4+1.20.1  porting_lib_recipe_book_categories: 2.3.4+1.20.1  porting_lib_tags: 3.0  porting_lib_tool_actions: 2.3.4+1.20.1  porting_lib_transfer: 2.3.4+1.20.1  porting_lib_utility: 2.3.4+1.20.1  predicate-api: 0.2.1+1.20.1  pride: 1.2.0+1.19.4  prism: 1.0.5  puzzlesaccessapi: 8.0.9  puzzlesapi: 8.1.7  puzzleslib: 8.1.25  reach-entity-attributes: 2.4.0  reacharound: 1.3.1  rechiseled: 1.1.6  reeses-sodium-options: 1.7.2+mc1.20.1-build.101  regions_unexplored: 0.5.6+1.20.1  rei-enchantment-info: 1.0.0  reicollapsibleentries: 3.1.1  resourcefulconfig: 2.1.2  resourcefullib: 2.1.29  rightclickharvest: 3.2.3+1.19.x-1.20.1-fabric  roughlyenoughitems: 12.1.785  roughlyenoughprofessions: 2.0.2  roughlysearchable: 2.6.0+1.20.1  sawmill: 1.20-1.4.3  scorchful: 0.6.5  searchables: 1.0.3  server_translations_api: 2.0.0+1.20  sgui: 1.2.2+1.20  skinlayers3d: 1.7.2  smallships: 2.0.0-b1.4  smwyg: 1.1.1  sodium: 0.5.8+mc1.20.1  sodium-extra: 0.5.4+mc1.20.1-build.115  sound_physics_remastered: 1.20.1-1.4.5  spark: 1.10.53  sparsestructures: 2.2.0  spawn: 1.0.3-fabric  spawnanimations: 1.9.4+mod  spawnermod: 1.2.4  spawners_plus: 4.0-1.20.1  spectrelib: 0.13.17+1.20.1  spruceui: 5.0.0+1.20  starlight: 1.1.2+fabric.dbc156f  statement: 4.2.8+1.14.4-1.20.1  statement_vanilla_compatibility: 1.0.1+1.16.5-1.17  stoneworks: 8.0.0  structory: 1.3.5  structory_towers: 1.0.7  supermartijn642configlib: 1.1.8+a  supermartijn642corelib: 1.1.17+a  supplementaries: 1.20-3.1.10  t_and_t: 1.12  talkbubbles: 1.0.8  taxfreelevels: 1.4.1  tclayer: 3.8.1+beta.14  tectonic: 2.4.1b  terrablender: 3.0.1.7  terraform-surfaces-api-v1: 7.0.2  terraform-wood-api-v1: 7.0.1  thermoo: 2.3.3  thermoo-patches: 1.0.3  toms_storage: 1.6.8  toms_trading_network: 0.3.0  tooltipfix: 1.1.1-1.20  tradingpost: 8.0.2  twigs: 3.1.0  universal-graves: 3.0.3+1.20.1  variantsandventures: 1.0.6  visuality: 0.7.1+1.20  visualworkbench: 8.0.0  voicechat: 1.20.1-2.5.26  watut: 1.20.1-1.1.3  whydoesmyglasssoundlikethat: 1.1.0  woodlands_extra: 1.3.1  wthit: 8.15.3  wunderlib: 1.1.5  xaerominimap: 24.6.1  xaeroworldmap: 1.39.0  xercapaint: fabric-1.20.1-1.0.1  xp_storage: 1.5.7+1.20.1  xp_storage_trinkets: 1.0+1.20.1  yet_another_config_lib_v3: 3.6.1+1.20.1-fabric  ysns: 2.0.2  yungsapi: 1.20-Fabric-4.0.6  yungsbridges: 1.20-Fabric-4.0.3  yungscavebiomes: 1.20.1-Fabric-2.0.0  yungsextras: 1.20-Fabric-4.0.3  zoomify: 2.14.2+1.20.1

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment] 2024-12-06 05:19
I guess its completely understandable that testing over 300 mods individually is impossible, especially since Furniture does not contain any classes or mechanics related to MobEffects like Mining Fatigue or any other MobEffect.

If the issue only happens in combination with other mods, its likely caused by a mod conflict where another mod might indirectly trigger this behavior.

Without specific log data or a clear way to reproduce the issue, its difficult for me to investigate further. I recommend systematically enabling and disabling mods to narrow down the conflict.

**Comment by satisfyu** [comment] 2024-12-11 19:41
No further information received. I will therefore close this issue. As already mentioned, the best approach would be to gradually remove mods to see which one it conflicts with.

**Closed by satisfyu** 2024-12-11 19:41 UTC
Labels: information needed
